=== kitkit922/xml-and-js/Project-1/automotive.dtd
<!ELEMENT automotive-data (manufacturers-data+)>
<!ELEMENT manufacturers-data (id, name, street, city, region?, country, carModels, cars)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT carModels (carModel+)>
<!ELEMENT carModel (id, name, year, usdPrice, cadPrice, euroPrice, poundPrice)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT usdPrice (#PCDATA)>
<!ELEMENT cadPrice (#PCDATA)>
<!ELEMENT euroPrice (#PCDATA)>
<!ELEMENT poundPrice (#PCDATA)>
<!ELEMENT cars (car+)>
<!ELEMENT car (vin, color, buyer)>
<!ELEMENT vin (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT buyer (#PCDATA)>

=== kitkit922/xml-and-js/Project-1/automotive-dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- To refer to a DTD in an XMLdocument -->
<!DOCTYPE automotive-data SYSTEM "automotive.dtd">

<!-- To link XSLT and XML documents -->
<?xml-stylesheet type="text/xsl" href="automotive.xsl"?>

<automotive-data>
    <manufacturers-data>
        <id>081df6a8-09fa-40aa-bc00-27ab14a9f216</id>
        <name>Chevrolet</name>
        <street>4659 American Lane</street>
        <city>Montaigu</city>
        <region>Pays de la Loire</region>
        <country>France</country>
        <carModels>
            <carModel>
                <id>9facefb2-503f-4a21-96e3-272fffadf5ed</id>
                <name>MPV</name>
                <year>2000</year>
                <usdPrice>$35852.42</usdPrice>
                <cadPrice>$40615.71</cadPrice>
                <euroPrice>&#8364;33338,73</euroPrice>
                <poundPrice>&#163;92221.34</poundPrice>
            </carModel>
            <carModel>
                <id>bcb685e0-8315-4015-91e4-44257b7d1e91</id>
                <name>Camry</name>
                <year>2003</year>
                <usdPrice>$39688.38</usdPrice>
                <cadPrice>$76556.45</cadPrice>
                <euroPrice>&#8364;99534,56</euroPrice>
                <poundPrice>&#163;76670.26</poundPrice>
            </carModel>
            <carModel>
                <id>6b222199-1992-4168-98cc-77a194072be6</id>
                <name>M</name>
                <year>2011</year>
                <usdPrice>$74122.16</usdPrice>
                <cadPrice>$98345.04</cadPrice>
                <euroPrice>&#8364;47275,87</euroPrice>
                <poundPrice>&#163;60432.34</poundPrice>
            </carModel>
        </carModels>
        <cars>
            <car>
                <vin>JTDKN3DU8F0938961</vin>
                <color>Violet</color>
                <buyer>rmissenden1x@cbslocal.com</buyer>
            </car>
            <car>
                <vin>WP0CA2A84FS421937</vin>
                <color>Aquamarine</color>
                <buyer>hhazeldene1y@admin.ch</buyer>
            </car>
            <car>
                <vin>WAUEF98E37A023346</vin>
                <color>Fuscia</color>
                <buyer>mwilliscroft1z@spiegel.de</buyer>
            </car>
            <car>
                <vin>19UUA9E50CA543243</vin>
                <color>Teal</color>
                <buyer>tcopestick20@unc.edu</buyer>
            </car>
            <car>
                <vin>1NXBU4EE7AZ391940</vin>
                <color>Purple</color>
                <buyer>jbaudrey21@diigo.com</buyer>
            </car>
            <car>
                <vin>3C6JD6EP7CG059927</vin>
                <color>Turquoise</color>
                <buyer>stunnah22@spotify.com</buyer>
            </car>
        </cars>
    </manufacturers-data>
    <manufacturers-data>
        <id>ea7f382b-d285-47f7-a671-f2c1e4b2ed0d</id>
        <name>Lincoln</name>
        <street>30 Barby Alley</street>
        <city>Noyon</city>
        <region>Picardie</region>
        <country>France</country>
        <carModels>
            <carModel>
                <id>e81573c7-a7f2-488c-ab55-4a059c05119c</id>
                <name>Thunderbird</name>
                <year>1989</year>
                <usdPrice>$91827.63</usdPrice>
                <cadPrice>$95758.28</cadPrice>
                <euroPrice>&#8364;35276,93</euroPrice>
                <poundPrice>&#163;94533.67</poundPrice>
            </carModel>
            <carModel>
                <id>ee579150-4e7b-43ce-be61-10847fdf607a</id>
                <name>Miata MX-5</name>
                <year>2003</year>
                <usdPrice>$70663.60</usdPrice>
                <cadPrice>$84159.72</cadPrice>
                <euroPrice>&#8364;32672,77</euroPrice>
                <poundPrice>&#163;16631.85</poundPrice>
            </carModel>
            <carModel>
                <id>7014e302-2e81-4c61-b02a-9ddf9437e2c8</id>
                <name>Ram Van B350</name>
                <year>1992</year>
                <usdPrice>$14259.75</usdPrice>
                <cadPrice>$50843.92</cadPrice>
                <euroPrice>&#8364;20204,36</euroPrice>
                <poundPrice>&#163;77350.43</poundPrice>
            </carModel>
        </carModels>
        <cars>
            <car>
                <vin>WAUNF78P38A124572</vin>
                <color>Blue</color>
                <buyer>astreeter1n@privacy.gov.au</buyer>
            </car>
            <car>
                <vin>WAUAF78E18A009563</vin>
                <color>Turquoise</color>
                <buyer>jtemby1o@xing.com</buyer>
            </car>
            <car>
                <vin>KMHFH4JG1FA970458</vin>
                <color>Aquamarine</color>
                <buyer>kvaller1p@4shared.com</buyer>
            </car>
            <car>
                <vin>WAU2GBFC2CN230998</vin>
                <color>Red</color>
                <buyer>acrosswaite1q@wsj.com</buyer>
            </car>
            <car>
                <vin>WAUVF98K89A984565</vin>
                <color>Teal</color>
                <buyer>lnicholl1r@godaddy.com</buyer>
            </car>
        </cars>        
    </manufacturers-data>
    <manufacturers-data>
        <id>74c4cb1a-65c3-4012-af6d-7dd921532ad7</id>
        <name>Ford</name>
        <street>820 Valley Edge Street</street>
        <city>La Seyne-sur-Mer</city>
        <region>Provence-Alpes-Côte d'Azur</region>
        <country>France</country>
        <carModels>
            <carModel>
                <id>b4750632-3546-442c-b303-485360818dc5</id>
                <name>Explorer</name>
                <year>2013</year>
                <usdPrice>$57828.44</usdPrice>
                <cadPrice>$63983.16</cadPrice>
                <euroPrice>&#8364;20016,38</euroPrice>
                <poundPrice>&#163;44682.78</poundPrice>
            </carModel>
            <carModel>
                <id>30ae99bf-02d0-465c-91ee-9f514479ad62</id>
                <name>300M</name>
                <year>2002</year>
                <usdPrice>$27315.20</usdPrice>
                <cadPrice>$68159.92</cadPrice>
                <euroPrice>&#8364;74252,65</euroPrice>
                <poundPrice>&#163;55092.93</poundPrice>
            </carModel>
            <carModel>
                <id>6b365628-92a7-4745-a7ea-1d6d8ebb4f02</id>
                <name>Trans Sport</name>
                <year>1995</year>
                <usdPrice>$93029.12</usdPrice>
                <cadPrice>$78635.77</cadPrice>
                <euroPrice>&#8364;67850,56</euroPrice>
                <poundPrice>&#163;52737.17</poundPrice>
            </carModel>
        </carModels>
        <cars>
            <car>
                <vin>1J4PN2GK8AW403803</vin>
                <color>Purple</color>
                <buyer>dmottershaw1i@senate.gov</buyer>
            </car>
            <car>
                <vin>5TDBW5G18FS612858</vin>
                <color>Maroon</color>
                <buyer>rdesesquelle1j@issuu.com</buyer>
            </car>
            <car>
                <vin>WBS3C9C53FP537356</vin>
                <color>Fuscia</color>
                <buyer>mroubottom1k@quantcast.com</buyer>
            </car>
            <car>
                <vin>1GD01ZCG6CF361384</vin>
                <color>Violet</color>
                <buyer>nhenrot1l@psu.edu</buyer>
            </car>
            <car>
                <vin>1FTWW3A58AE430459</vin>
                <color>Violet</color>
                <buyer>qkelloch1m@sitemeter.com</buyer>
            </car>
        </cars>
    </manufacturers-data>
    <manufacturers-data>
        <id>485a6a77-c251-4920-b00d-a9c96f8b0037</id>
        <name>Chrysler</name>
        <street>8 Killdeer Place</street>
        <city>Creil</city>
        <region>Picardie</region>
        <country>France</country>
        <carModels>
            <carModel>
                <id>81af56c0-0b29-4f32-89c3-42f899c271f9</id>
                <name>Ridgeline</name>
                <year>2011</year>
                <usdPrice>$63461.61</usdPrice>
                <cadPrice>$53755.91</cadPrice>
                <euroPrice>&#8364;10147,12</euroPrice>
                <poundPrice>&#163;48835.51</poundPrice>
            </carModel>
            <carModel>
                <id>ca04026c-429b-4822-9334-2f37f4e14646</id>
                <name>RX Hybrid</name>
                <year>2010</year>
                <usdPrice>$10441.06</usdPrice>
                <cadPrice>$19802.60</cadPrice>
                <euroPrice>&#8364;50283,48</euroPrice>
                <poundPrice>&#163;98516.76</poundPrice>
            </carModel>
            <carModel>
                <id>2a046362-94fa-4fad-9971-ee8793bce80a</id>
                <name>Sonoma Club Coupe</name>
                <year>1994</year>
                <usdPrice>$87244.40</usdPrice>
                <cadPrice>$18099.62</cadPrice>
                <euroPrice>&#8364;38217,23</euroPrice>
                <poundPrice>&#163;26810.96</poundPrice>
            </carModel>
        </carModels>
        <cars>
            <car>
                <vin>5LMJJ2H50DE219118</vin>
                <color>Red</color>
                <buyer>lbane1e@hud.gov</buyer>
            </car>
            <car>
                <vin>WDDHH8JB4FB808428</vin>
                <color>Violet</color>
                <buyer>aimpleton1f@ameblo.jp</buyer>
            </car>
            <car>
                <vin>WAULC68E25A513742</vin>
                <color>Goldenrod</color>
                <buyer>seymer1g@microsoft.com</buyer>
            </car>
            <car>
                <vin>WAUEH98E16A740482</vin>
                <color>Orange</color>
                <buyer>jleaves1h@rediff.com</buyer>
            </car>
        </cars>        
    </manufacturers-data>
    <manufacturers-data>
        <id>fc8c76c4-9a64-44e8-ba64-f17565d9a467</id>
        <name>Lamborghini</name>
        <street>959 Rusk Terrace</street>
        <city>Chalon-sur-Saône</city>
